config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'
  get 'home/about' => 'home#about'


  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]

  get 'posts/like_posts' => 'posts#like_posts'
  get 'posts/following_posts' => 'posts#following_posts'
  get 'posts/follower_posts' => 'posts#follower_posts'
  get 'posts/breeds' => 'posts#breeds'

  resources :posts do
     resource :comments, only: [:create, :destroy]
     resource :likes, only: [:create, :destroy]
  end

  get '/search' => 'search#index', as: 'search'
  get '/search/index2' => 'search#index2'
  get '/search/result' => 'search#result'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :plofile_image, destroy: false
  belongs_to :favorite_breed

  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :user_name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: {maximum: 50}
  validates :favorite_breed, presence: true

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
    callback_from :twitter
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

    private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth'].except("extra")
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.all.order("created_at DESC").page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    #フォロワー順にユーザーを取得する
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  def show
  	@user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).reverse_order
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def following
      @user = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

   private
   def user_params
     params.require(:user).permit(:name, :user_name, :profile_image)
   end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォロー", class: "btn btn-sm btn-info follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-sm follow-btn" %>
<% end %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render 'layouts/searchform' %>
    </div>

    <div class="col-md-9">
        <h3>ユーザー投稿</h3>
            <div class="post-list">
                <% @posts.each do |post| %>
                    <%= link_to post_path(post),class: "post-list-items" do %>
                        <%= render 'posts/post_index', post: post %>
                    <% end %>
                <% end %>
            </div>
        </div>

        <div class="col-md-offset-6 col-md-6"><%= paginate @posts %></div>
    </div>
</div>

app/views/users/posts.html.erb
<div class="row">
	<div class="col-xs-3">
        <%= render 'layouts/searchform' %>
	</div>

	<div class="col-xs-9">
		<div class="#">
			<h2>投稿一覧</h2>
            <div class="post-list clearfix">
                <% @posts.each do |post| %>
                    <%= link_to post_path(post.id) do %>
                        <%= render 'post_index', post: post %>
                    <% end %>
                <% end %>
            </div>
		</div>

	</div>
</div>

app/views/users/show.html.erb
<div class="user-show-wrapper">
<div class="row">
	<div class="col-md-4 col-sm-offset-2">
		<h3>ユーザーページ</h3>
	</div>
</div>

<div class="row">
	<div class="col-sm-4 col-sm-offset-7">
		<% if @user.id == current_user.id %>
        	<u><%= link_to ">>プロフィール編集", edit_user_registration_path(@user), class: "edit_plofile" %></u>
    	<% end %>
	</div>
</div>


<div class="row">
<div class="col-md-8 col-md-offset-1">
	<table class="box6">
		<tr class="info-menu">
          <td rowspan="3"><%= attachment_image_tag @user, :plofile_image, format: 'jpeg', class: "img-circle profile-show-image", fallback: "no_image.jpg" %></td>
    		<td class="info-menu-left">名前</td>
    		<td><%= @user.user_name %></td>
    </tr>

		<tr class="info-menu">
    		<td class="info-menu-left">好きな猫種</td>
    		<td><% if @user.favorite_breed == nil %>
              <%= "選択してください" %>
            <% else %>
               <%= @user.favorite_breed.cat_breed %>
            <% end %>
        </td>
    </tr>

		<tr class="info-menu">
    		<td class="info-menu-left">自己紹介</td>
    		<td><%= @user.introduction %></td>
    </tr>
  </table>
</div>
</div>

<div class="row">
    <div class="col-md-2 col-sm-offset-2 show-follow">
      <%= render 'stats' %>

      <%= render 'follow_form' %>

		<% unless @user.id == current_user.id %>
  			<% if @isRoom == true %>
    			<p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="far fa-envelope">DMを送る</a></p>
  			<% else %>
    			<%= form_for @room do |f| %>
      			<%= fields_for @entry do |e| %>
        			<%= e.hidden_field :user_id, value: @user.id %>
      			<% end %>
      			<%= f.submit "DMを送る", class:"user-show-chat"%>
    			<% end %>
  			<% end %>
		<% end %>

      <div class="dm-envelope">
        <% if @user.id == current_user.id %>
          <i class="far fa-envelope"></i><%= link_to "DM一覧", rooms_path,class: "dm-index" %>
        <% end %>
      </div>

    </div>
</div>

<div class="row">
	<div class="col-md-8 col-sm-offset-2">
		<h3>投稿一覧</h3>
			<% @posts.each do |post| %>
        <%= link_to post_path(post),class: "post-show-items" do %>
				<%= attachment_image_tag post, :image, format: 'jpeg', fallback: "no_image.jpg", class: "userpost-image" %>
        <% end %>
			<% end %>
    </div>
</div>
</div>

app/views/users/show_follow.html.erb
<div class="title col-md-offset-4 col-md-8">
    <div class="index-header">
        <h3>フォロー中</h3>
    </div>

      <table class="table table-hover" style="width: 500px;  height: 50px;">
      	<thead>
	      <tr class="active">
	      	<th width="10%"></th>
	        <th width="10%"></th>
			<th width="80%"></th>
	      </tr>
	    </thead>
	    <tbody style="background-color: rgba(255, 255, 255, 0.3);">
	      <% @user.followings.each do |user| %>
	      <tr>
	      	<td><%= attachment_image_tag user, :plofile_image, format: 'jpeg', class: "img-circle profile-follow-image", fallback: "no_image.jpg" %></td>
	      	<td><%= link_to user.user_name, user_path(user), class: "follow-index" %></td>
	      	<td><p class="follow-index"><%= user.introduction %></p></td>
	      </tr>
	      <% end %>
      	</tbody>
      </table>

</div>

app/views/users/show_follower.html.erb
<div class="title col-md-offset-4 col-md-8">
    <div class="index-header">
        <h3>フォロワー</h3>
    </div>

      <table class="table table-hover" style="width: 500px;  height: 50px;">
      	<thead>
	      <tr class="active">
	      	<th width="10%"></th>
	        <th width="10%"></th>
			<th width="80%"></th>
	      </tr>
	    </thead>
	    <tbody style="background-color: rgba(255, 255, 255, 0.3);">
	      <% @user.followers.each do |user| %>
	      <tr>
	      	<td><%= attachment_image_tag user, :plofile_image, format: 'jpeg', class: "img-circle profile-follow-image", fallback: "no_image.jpg" %></td>
	      	<td><%= link_to user.user_name, user_path(user), class: "follow-index" %></td>
	      	<td><p class="follow-index"><%= user.introduction %></p></td>
	      </tr>
	      <% end %>
      	</tbody>
      </table>

</div>