config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'
  get 'home/about' => 'home#about'


  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]

  get 'posts/like_posts' => 'posts#like_posts'
  get 'posts/following_posts' => 'posts#following_posts'
  get 'posts/follower_posts' => 'posts#follower_posts'
  get 'posts/breeds' => 'posts#breeds'

  resources :posts do
     resource :comments, only: [:create, :destroy]
     resource :likes, only: [:create, :destroy]
  end

  get '/search' => 'search#index', as: 'search'
  get '/search/index2' => 'search#index2'
  get '/search/result' => 'search#result'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  attachment :image
  belongs_to :user


  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 200}

 def liked_by?(user)
      likes.where(user_id: user.id).exists?
 end

  def save_tags(tag_list)
    delete_count = 0
    if tag_list.empty?

      if post_tag = PostTag.where(post_id: self.id)
        post_tag.delete_all
      end
    end
    tag_list.uniq.each do |tag|
      # 受け取った値を小文字に変換して、DBを検索して存在しない場合は
      # find_tag に nil が代入され　nil となるのでタグの作成が始まる
      unless find_tag = Tag.find_by(tag_name: tag.downcase)
        begin
          # create メソッドでタグの作成
          # create! としているのは、保存が成功しても失敗してもオブジェクト
          # を返してしまうため、例外を発生させたい
          self.tags.create!(tag_name: tag)

        # 例外が発生すると rescue 内の処理が走り nil となるので
        # 値は保存されないで次の処理に進む
        rescue
          nil
        end
      else

        if delete_count == 0
        post_tag = PostTag.where(post_id: self.id)
        post_tag.delete_all
        delete_count = 1
        end
            # DB にタグが存在した場合、中間テーブルにブログ記事とタグを紐付けている
        PostTag.create!(post_id: self.id, tag_id: find_tag.id)

      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@posts = Post.order("created_at DESC").page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  def new
  	@post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      tag_list = tag_params[:tag_names].delete(" ").split(",")
      tags = Vision.get_image_data(@post.image)
      cats = ["Cat","Cats"]
      if cats.any? { |t| tags.include?(t) }
        @post.save_tags(tag_list)
        redirect_to post_path(@post)
      else
        @post.destroy
        flash[:danger] = '猫の画像を選択してください'
        redirect_to new_post_path
      end
    else
        render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    tag_list = tag_params[:tag_names].delete(" ").split(",")
    @post.update(post_params)
    @post.save_tags(tag_list)
    redirect_to post_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def like_posts
    @user = current_user
    @likes = Like.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    #フォロワー順にユーザーを取得する
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  def following_posts
    @user = current_user
    @users = @user.followings.order("created_at DESC").page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  def follower_posts
    @user = current_user
    @users = @user.followers.order("created_at DESC").page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  def breeds
    @users = User.where(favorite_breed_id: current_user.favorite_breed.id).where.not(id: current_user.id).page(params[:page]).per(20)
    @follow_count_id_hash = Relationship.group(:following_id).order('count_following_id DESC').limit(3).count(:following_id)
    @follow_count_id = @follow_count_id_hash.keys
    @follow_count_user = User.where(id: @follow_count_id).index_by(&:id)
  end

  private

   def post_params
     params.require(:post).permit(:title, :content, :image, :remove_image)
   end

    def tag_params
      params.require(:post).permit(:tag_names)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
            <p><%= comments.count %>件コメント</p>
        <ol>
        <% comments.each do |comment| %>
            <li class="comment">
                <div class="comment-body bb">
                    <div class="comment-avatar">
                        <div class="avatar col-xs-12">
                            <%= attachment_image_tag comment.user, :plofile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                            <%= comment.comment %>
                            <% if comment.user == current_user %>
                            <%= link_to "削除", post_comments_path(comment), method: :delete, remote: true %>
                            <% end %>
                        </div>
                    </div>
                    <div class="comment-text">
                        <div class="comment-author clearfix">
                            <%= link_to comment.user.user_name, user_path(comment.user) %>
                            <span class="comment-date"><%= comment.created_at.strftime('%Y/%m/%d') %></span>
                            </span>
                        </div>
                    </div>
                </div>
            </li>
        <% end %>
        </ol>

app/views/posts/_likesform.html.erb
<% if post.liked_by?(current_user) %>
    <%= link_to post_likes_path(post), method: :delete, remote: true, class: "post-list-items" do %>
        <i class="fas fa-paw" aria-hidden="true" style="color: black;"></i>
        <%= post.likes.count %> いいね
    <% end %>
<% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true, class: "post-list-items" do %>
        <i class="fas fa-paw" aria-hidden="true"></i>
        <%= post.likes.count %> いいね
    <% end %>
<% end %>

app/views/posts/_post_index.html.erb
<table class="post-box">
    <tr>
        <td colspan=2>
            <%= link_to user_path(post.user),class: "post-list-items" do %>
                <%= attachment_image_tag post.user, :plofile_image, :fill, 30, 30, format: 'jpeg', class: "img-circle pull-left profile-thumb post-icon", fallback: "no_image.jpg" %>
             <% end %>
            <%= link_to post.user.user_name, user_path(post.user),class: "post-list-items" %>
        </td>
    </tr>
    <tr>
        <td colspan=2><%= attachment_image_tag post, :image, format: 'jpeg', fallback: "no_image.jpg",class: "post-images" %>
        </td>
    </tr>
    <tr>
        <td class="post_<%= post.id %>"><%= render 'posts/likesform', post: post %>
        </td>
        <td><%= link_to post.comments.count, post_path(post.id),class: "post-list-items" %>コメント<i class="far fa-comment-dots">
        </td>
    </tr>
</table>

app/views/posts/breeds.html.erb
<div class="row">
	<div class="col-xs-3">
        <%= render 'layouts/searchform' %>
	</div>

	<div class="col-xs-9">
		<h3>おすすめ</h3>
            <div class="post-list">

            <% @users.each do |user| %>
              <% @posts = Post.where(user_id: user.id).limit(1).order("created_at DESC") %>
                <% @posts.each do |post| %>
                    <%= link_to post_path(post.id) do %>
                        <%= render 'post_index', post: post, user: user %>
                    <% end %>
                <% end %>
            <% end %>
            </div>
		</div>

		<div class="col-xs-offset-5 col-xs-6"><%= paginate @users %></div>
	</div>
</div>

app/views/posts/edit.html.erb
	<div class="row">
		<div class="col-xs-offset-1 col-xs-8">
			<h3><span>　投稿編集　</h3></span>
		</div>
	</div>

	<div class="newpost-wrapper">
		<%= form_with model: @post, local: true do |post| %>

    			<% if @post.errors.any? %>
        			<div id="error_explanation">
            			<h2><%= pluralize(@post.errors.count, "error") %> prohibited this upload from being saved:</h2>
        			</div>
    			<% end %>

			<div class="col-xs-4 col-xs-offset-1">

				<div class="post_image_field">
  					<%= attachment_image_tag @post, :image, class: "image_prev", id: "img_prev" if @post.image %>
  					<%= post.hidden_field :image_cache %>
  					<%= post.file_field :image, :id => 'post_post_img' %>
				</div>
				<p><%= post.check_box :remove_image %>画像を削除する</p>

			</div>

			<div class="col-xs-7">
				<div class="col-xs-12">
					<div class="col-xs-1">
						<p>Title:</p>
					</div>
					<div class="col-xs-9">
						<p><%= post.text_field :title %></p>
					</div>
				</div>

				<div class="col-xs-12">
					<div class="col-xs-1">
						<p>Text:</p>
					</div>
					<div class="col-xs-9">
						<p><%= post.text_area :content, size: "50x10", placeholder: "200字以内" %></p>
					</div>
				</div>

				<div class="col-xs-12">
					<div class="col-xs-1">
						<p>Tag:</p>
					</div>
					<div class="col-xs-9">
						<p id="post-tags"><%= post.text_area :tag_names, value: @post.tags.map(&:tag_name).join(","), size: "20x1" %><span class="tag-message">複数は( , )で区切る</span></p>
					</div>
				</div>

				<div class="col-xs-12">
					<div class="col-xs-offset-1 col-xs-3">
						<%= post.submit '更新', class: "btn btn-primary btn-block" %>
					</div>
				</div>
			</div>
		<% end %>
	</div>

app/views/posts/follower_posts.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render 'layouts/searchform' %>
    </div>

    <div class="col-md-9">
        <h3>フォロワー投稿</h3>
            <div class="post-list">

              <% @users.each do |user| %>
              <% @posts = Post.where(user_id: user.id).limit(1).order("created_at DESC") %>
                <% @posts.each do |post| %>
                        <%= link_to post_path(post.id),class: "post-list-items" do %>
                        <%= render 'post_index', post: post, user: user %>
                    <% end %>
                <% end %>
              <% end %>
            </div>
        <div class="col-md-offset-6 col-md-6"><%= paginate(@users) %></div>
    </div>
</div>

app/views/posts/following_posts.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render 'layouts/searchform' %>
    </div>

    <div class="col-md-9">
        <h3>フォローユーザー投稿</h3>
            <div class="post-list">

              <% @users.each do |user| %>
              <% @posts = Post.where(user_id: user.id).limit(1).order("created_at DESC") %>
                <% @posts.each do |post| %>
                        <%= link_to post_path(post.id), class: "post-list-items" do %>
                        <%= render 'post_index', post: post, user: user %>
                        <% end %>
                <% end %>
              <% end %>
            </div>
        <div class="col-md-offset-6 col-md-6"><%= paginate(@users) %></div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-3">
        <%= render 'layouts/searchform' %>
	</div>

	<div class="col-md-9">
		<h3>投稿一覧</h3>
            <div class="post-list">

                <% @posts.each do |post| %>
                    <%= link_to post_path(post),class: "post-list-items" do %>
                        <%= render 'post_index', post: post %>
                    <% end %>
                <% end %>

            </div>
		<div class="col-md-offset-6 col-md-6"><%= paginate @posts %></div>
	</div>
</div>

app/views/posts/like_posts.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render 'layouts/searchform' %>
    </div>

    <div class="col-md-9">
        <h3>お気に入り</h3>
            <div class="post-list">
                <% @likes.each do |like| %>
  					<% post = Post.find_by(id: like.post_id) %>
  					<% user = User.find_by(id: post.user_id) %>
                        <%= link_to post_path(post.id), class: "post-list-items" do %>
                        <%= render 'post_index', post: post, user: user %>
                    <% end %>
                <% end %>
            </div>
		</div>
	  <div class="col-md-offset-6 col-md-6"><%= paginate(@likes) %></div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<h3><span>　新規投稿　</h3></span>
			<div class="flash_danger">
			  <%= flash[:danger] %>
			</div>
		</div>
	</div>

	<div class="newpost-wrapper">
		<%= form_with model: @post, local: true do |post| %>

    			<% if @post.errors.any? %>
        			<div id="error_explanation">
            			<h2><%= pluralize(@post.errors.count, "error") %> prohibited this upload from being saved:</h2>
        			</div>
    			<% end %>

			<div class="col-md-4 col-md-offset-1">

				<div class="post_image_field">
  					<%= image_tag @post.image, class: "new-post-image" if @post.image %>
  					<%= post.hidden_field :image_cache %>
  					<img id="img_prev" width=400 height=300 src="#" class="img_thumbnail  hidden"/>
  					<%= post.file_field :image, :id => 'post_post_img' %>
				</div>

				<p><%= post.check_box :remove_image %>画像を削除する</p>
			</div>

			<div class="col-md-7 new-post-left">
				<div class="col-md-12">
					<div class="col-md-1">
						<p>Title:</p>
					</div>
					<div class="col-md-9">
						<p><%= post.text_field :title %></p>
					</div>
				</div>

				<div class="col-md-12">
					<div class="col-md-1">
						<p>Text:</p>
					</div>
					<div class="col-md-9">
						<p><%= post.text_area :content, placeholder: "200字以内", class: "post-content" %></p>
					</div>
				</div>

				<div class="col-md-12">
					<div class="col-md-1">
						<p>Tag:</p>
					</div>
					<div class="col-md-11">
						<p id="post-tags"><%= post.text_field :tag_names, class: "post-tag-input", placeholder: "20字以内" %><span class="tag-message"> ( , )で区切る</span></p>
					</div>
				</div>

				<div class="col-md-12">
					<div class="post-submit col-md-offset-1 col-md-3">
						<%= post.submit '投稿', class: "btn btn-primary btn-block" %>
					<% end %>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="post-show-wrapper">
	<div class="col-md-4 col-md-offset-1">

		<%= attachment_image_tag @post, :image, format: 'jpeg', fallback: "no_image.jpg", class: "post-show-image" %>

		<h3><%= @post.title %></h3>


		<div class="post-likes col-md-12">
			<div class="post_<%= @post.id %>">
				<%= render 'posts/likesform', post: @post %>
			</div>
		</div>

		<div class="post-tag col-md-12">
			<% @post.tags.each do |tag| %>
  				<p>#<%= tag.tag_name %></p>
			<% end %>
		</div>

		<% if @post.user == current_user %>
		<p><%= link_to "編集",edit_post_path(@post), class: "btn btn-success" %>
		<%= link_to "削除",post_path(@post.id), method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %></p>
		<% end %>
  	</div>

	<div class="col-md-5">
		<div class="post-info col-md-2">
			<%= attachment_image_tag @post.user, :plofile_image, format: 'jpeg', class: "img-circle pull-left post-profile-image", fallback: "no_image.jpg" %>
			<p><%= link_to @post.user.user_name, user_path(@post.user) %></p>
		</div>

		<div class="box10 col-md-10">
			<p><%= @post.content %></p>
		</div>

		<div class="post-comment-form col-md-10 col-md-offset-2">
		<%= form_with model:[@post, @comment], data: {remote: true} do |f| %>
        	<p><%= f.text_area :comment, rows:'2', class: "form-control",placeholder: "コメントをここに" %></p>
    		<%= f.submit "送信", class: "btn btn-sm pull-right" %>
		<% end %>
		</div>

		<div class="col-md-12">
    		<div class="comment_<%= @post.id %>">
      			<%= render 'posts/comment', comments: @post.comments %>
    		</div>
		</div>
	</div>
</div>