config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'
  get 'home/about' => 'home#about'


  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:index, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]

  get 'posts/like_posts' => 'posts#like_posts'
  get 'posts/following_posts' => 'posts#following_posts'
  get 'posts/follower_posts' => 'posts#follower_posts'
  get 'posts/breeds' => 'posts#breeds'

  resources :posts do
     resource :comments, only: [:create, :destroy]
     resource :likes, only: [:create, :destroy]
  end

  get '/search' => 'search#index', as: 'search'
  get '/search/index2' => 'search#index2'
  get '/search/result' => 'search#result'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
    belongs_to :post
    validates :comment, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :email, presence: true, length: {maximum:255}
  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite_breed.rb
class FavoriteBreed < ApplicationRecord
	has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room
  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  attachment :image
  belongs_to :user


  validates :title, presence: true
  validates :content, presence: true, length: {maximum: 200}

 def liked_by?(user)
      likes.where(user_id: user.id).exists?
 end

  def save_tags(tag_list)
    delete_count = 0
    if tag_list.empty?

      if post_tag = PostTag.where(post_id: self.id)
        post_tag.delete_all
      end
    end
    tag_list.uniq.each do |tag|
      # 受け取った値を小文字に変換して、DBを検索して存在しない場合は
      # find_tag に nil が代入され　nil となるのでタグの作成が始まる
      unless find_tag = Tag.find_by(tag_name: tag.downcase)
        begin
          # create メソッドでタグの作成
          # create! としているのは、保存が成功しても失敗してもオブジェクト
          # を返してしまうため、例外を発生させたい
          self.tags.create!(tag_name: tag)

        # 例外が発生すると rescue 内の処理が走り nil となるので
        # 値は保存されないで次の処理に進む
        rescue
          nil
        end
      else

        if delete_count == 0
        post_tag = PostTag.where(post_id: self.id)
        post_tag.delete_all
        delete_count = 1
        end
            # DB にタグが存在した場合、中間テーブルにブログ記事とタグを紐付けている
        PostTag.create!(post_id: self.id, tag_id: find_tag.id)

      end
    end
  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post
	attachment :image
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id,presence:true
  validates :tag_id,presence:true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save :downcase_tag_name

  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :tag_name, presence: true, length: { maximum: 20 }

    private
    # タグ名を小文字に変換
    def downcase_tag_name
      self.tag_name.downcase!
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :plofile_image, destroy: false
  belongs_to :favorite_breed

  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :user_name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: {maximum: 50}
  validates :favorite_breed, presence: true

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_searchform.html.erb
<div class="sidemenu col-xs-10 col-xs-offset-1">
	<h3>投稿一覧</h3>
	<ul>
		<li><%= link_to "ユーザー", users_path %></li>
		<li><%= link_to "お気に入り", posts_like_posts_path %></li>
		<li><%= link_to "フォロー", posts_following_posts_path %></li>
		<li><%= link_to "フォロワー", posts_follower_posts_path %></li>
		<li><%= link_to "おすすめ", posts_breeds_path %></li>
	</ul>

	<br>
	<%= form_with url: search_path, method: :get, local: true do |f| %>
  		<%= f.text_field :q, placeholder: "タグワードを入力" %>
  		<%= f.submit "検索" %>
	<% end %>
	<br>
	<br>

    <div class="popular">
      <p class="popular-headline" style="display: inline-block; border-bottom: double;">人気ユーザー</p>
    	<div class="popular-box">
      		<% @follow_count_id.each do |user| %>
            	<table class="popular-users">
              		<tr class="popular-name">
              			<td rowspan="2"><%= attachment_image_tag @follow_count_user[user], :plofile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
              			</td>
              			<td><p><span class="popular-username"><%= link_to @follow_count_user[user].user_name, user_path(user) %></span></td>
        			    </tr>
        			    <tr>
                    <td><p><%= @follow_count_user[user].followers.count %>フォロワー</p></td>
        			    </tr>
        		  </table>
      		<% end %>
    	</div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyanstagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="container">
  <header class="nav navbar-fixed-top">

  <div class="el_humburger">
    <span class="top"></span>
    <span class="middle"></span>
    <span class="bottom"></span>
  </div>

  <div id="navigation" class="navigation">
    <div class="navigation_screen">
      <nav class="navigation_wrapper">
        <div class="navigation_item"><%= link_to "ユーザー", users_path %></div>
        <div class="navigation_item"><%= link_to "お気に入り", posts_like_posts_path %></div>
        <div class="navigation_item"><%= link_to "フォロー", posts_following_posts_path %></div>
        <div class="navigation_item"><%= link_to "フォロワー", posts_follower_posts_path %></div>
        <div class="navigation_item"><%= link_to "おすすめ", posts_breeds_path %></div>
        <div class="navigation_item"><%= link_to "お問い合わせ", new_contact_path %></div>
      </nav>
    </div>
  </div>


    <div class="nav-menu">
        <div class="nav navbar-nav navbar-left">
          <%= link_to image_tag('logo.png', class: "logo"), root_path %>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Top", posts_path, class: "nav-menu" %></li>
              <li><%= link_to "投稿する", new_post_path, class: "nav-menu" %></li>
              <li><%= link_to "マイページ", user_path(current_user.id), class: "nav-menu" %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-menu" %></li>
            <% else %>
              <li><%= link_to "Home", root_path, class: "nav-menu", data: {turbolinks: false } %></li>
              <li><%= link_to "About", home_about_path, class: "nav-menu", data: {turbolinks: false } %></li>
              <li><%= link_to "Sign up", new_user_registration_path, class: "nav-menu", data: {turbolinks: false } %></li>
              <li><%= link_to "Log in", new_user_session_path, class: "nav-menu", data: {turbolinks: false } %></li>
            <% end %>
          </ul>
      </div>
    </header>

    <main class="container-fluid body">
      <%= yield %>
    </main>

    <footer>
      <div class="footer-default">
        <div class="footer-contact">
          <%= link_to "お問い合わせ ", new_contact_path, class: "footer-contact-logo" %>
        </div>
        <div class="footer-right">
          <p>©DMM WEBCAMP, All Right Reserved. </p>
        </div>
      </div>

    <% if user_signed_in? %>
      <div class="footer-sp">
        <ul>
          <li><%= link_to "", posts_path, class: "fas fa-cat fa-2x" %></li>
          <li><%= link_to "",search_index2_path, class: "fas fa-search fa-2x" %></li>
          <li><%= link_to "",new_post_path, class: "far fa-plus-square fa-2x" %></li>
          <li><%= link_to "",user_path(current_user.id), class: "fas fa-user fa-2x" %></li>
          <li><%= link_to "",rooms_path, class: "far fa-envelope fa-2x" %></li>
        </ul>
      </div>
    <% end %>
    </footer>
 </div>
  </body>

</html>